struct TestAnalysis {
    char question[80];
    int correctAnswer;
    int studentAnswer;
};
struct ResultRecord {
    char name[80];
    char time[80];
    float result;
    char testType[80]; 
};
int menu(char** ppChoices);
int selectTypeOfQuestions();
void practice();
void test();
void createSession(struct TestAnalysis *pAnalysis, int numberOfQuestions, int sessionType);
void generateQuestionAddition(struct TestAnalysis *pAnalysis);
void generateQuestionSubtraction(struct TestAnalysis *pAnalysis);
int generateNumber();
void getTwoNumbers(int *pX, int *pY, int);
int getNumberFromStdin();
int assertAnswer(int expected, int provided);
char* correctAnswer();
char* inCorrectAnswer();
char* generateAnswer();
void saveToFile(float result, char *pName, int choice);
void displayPreviousResults();
void displayBestResult();
void displayMyResults();
void display5BestResults();
void highScores();